mq:
  type: mqtt
  mqtt:
    host: localhost
    port: 1883
  kafka:
    brokers:
      - localhost:9092

serviceId: testlazy
project: 625f6dbf5433487131f09ff9

driver:
  id: go-driver-mqtt-demo
  name: 测试驱动

log:
  level: 4
  format: json


driverGrpc:
  host: localhost
  port: 9224
  healthRequestTime: 10
  waitTime: 5
