mq:
  type: mqtt
  mqtt:
    host: 127.0.0.1
    port: 1883

serviceId: 62678dee5a13cc647f571640
project: 625f6dbf5433487131f09ff7

driver:
  id: test
  name: 测试驱动

log:
  level: 4

driverGrpc:
  host: 127.0.0.1
  #  host: 192.168.2.130
  port: 9224
  healthRequestTime: 10
  waitTime: 5
