mq:
  type: mqtt
  mqtt:
    host: 121.89.244.23
    port: 1883

serviceId: 64f847d563d1482d33753c25
project: 625f6dbf5433487131f09ff9

driver:
  id: go-driver-mqtt-demo
  name: 测试驱动

log:
  level: 4
  format: json


driverGrpc:
  host: localhost
  port: 9224
  healthRequestTime: 10
  waitTime: 5
