host: localhost # 接口服务地址
port: 80 # 接口服务端口

ws:
  health: 30
  interval: 10

credentials:
  ak: ak # 平台ak
  sk: sk # 平台sk

mqtt:
  host: localhost  # 消息队列地址
  port: 1883 # 消息队列端口

driver:
  id: 驱动id # 驱动唯一标识
  name: 驱动name # 驱动名称

log:
  level: 日志等级 # debug||info||warn||error

