mq:
  type: mqtt
  mqtt:
    host: localhost
    port: 1883
  kafka:
    brokers:
      - localhost:9092

serviceId: 64f847d563d1482d33753c25
project: zq

driver:
  id: go-driver-mqtt-demo
  name: 测试驱动

log:
  level: 5
  format: json


driverGrpc:
  host: localhost
  port: 9224
  healthRequestTime: 10s
  waitTime: 5s
